# Enable Spring Boot DevTools
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      additional-exclude: static/**,public/**

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=commercial
    username: takhoa1
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  security:
    user:
      name: abc
      password: abc

jwt:
  secret: secretPassword
